import type { Metadata } from "next";
import { Inter, Montserrat,Roboto_Mono } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const montserrat = Montserrat({ subsets: ["latin"] , weight: ["100", "200", "300", "400","500", "600", "700"], variable: "--font-montserrat" })
const roboto = Roboto_Mono({ subsets: ["latin"] , weight: [ "100", "200", "300", "400","500", "600", "700"], variable: "--font-roboto" })

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${roboto.variable} ${inter.className}`}>{children}</body>
    </html>
  );
}
